# Generated by Django 5.1.3 on 2024-11-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_next',
            new_name='choice_text',
        ),
    ]
